apiVersion: v1
kind: Service
metadata:
  namespace: ui
  name: nxt-ui-users-dev
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 443
      nodePort: 30225
      targetPort: 443
  selector:
    app: nxt-ui-users-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ui
  name: nxt-ui-users-dev
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: nxt-ui-users-dev
  template:
    metadata:
      labels:
        app: nxt-ui-users-dev
    spec:
      containers:
        - name: nxt-ui-users-dev
          image: CONTAINER_IMAGE
          ports:
            - containerPort: 443
          resources:
            requests:
              memory: '512Mi'
              cpu: '250m'
            limits:
              memory: '1024Mi'
              cpu: '500m'
